apiVersion: v1
kind: Service
metadata:
  name: zgh-sampleapp-service
spec:
  selector:
    app: zgh-sampleapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000
  type: NodePort