version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_db
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - app-data:/app
      - /app/.git
    ports:
      - 8000:8000
    depends_on:
      - db

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py migrate
    volumes:
      - .:/app
      - app-data:/app
      - /app/.git
    depends_on:
      - db

volumes:
  db-data:
  app-data:
