apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zgh-sampleapp-certificate
spec:
  dnsNames:
  - 'zgh.dacdevops.ru'
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: zgh-sampleapp-cert