apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zgh-sampleapp
 
resources:
  - ../../base
  - certificate.yaml
  - namespace.yaml

images:
  - name: bob245567/myapp:main
  - name: nginx
    newName: nginx
    newTag: 1.23.2-alpine
